name: 'Quality pipeline'
description: 'Run tests, test coverage and lint'
runs:
  using: "composite"
  steps:

    - name: Run tests capturing coverage
      run: |
        npm run test:coverage
      shell: bash

    - name: Check coverage
      run: |
        npm run test:coverage:check
      shell: bash

    - name: Run lint
      run: |
        npm run lint
      shell: bash
